# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/ubuntu-12.04-i386"
  config.vm.network "public_network", :bridge => "{{ bridged_network }}", :ip => "{{ server_ip }}"
  # Mount parent directory, because Vagrant is executed from directory "cache"
  config.vm.synced_folder "../files", "/vagrant"
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbook.yml"
      ansible.extra_vars = { :action => 'provision' }
  end
end